# Setup
title:               Joe Celentano
#tagline:             ''
description:         'Dad, Developer, Life Debugger. Building, diagnosing and debugging what seems like everything in my life.'
url:                 http://www.joecelentano.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Joe Celentano
  url:               https://www.linkedin.com/in/josephcelentano/
  email:             joe@joecelentano.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
show_downloads: "false"
google_analytics_id: #UA-XXXX-Y
theme: jekyll-theme-hacker
