# Setup
title:               Joe Celentano
tagline:             'Dad, Developer, Life Debugger'
description:         'Building, diagnosing and debugging what seems like the everything in my life.'
url:                 http://www.joecelentano.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Joe Celentano
  url:               https://www.linkedin.com/in/josephcelentano/
  email:             joe@joecelentano.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

theme: jekyll-theme-hacker
